# Generated by Django 4.1.7 on 2023-03-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False)),
                ('is_dislike', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_receiver', to='account.profile', verbose_name='profile_id - На кого поставили лайк/дизлайк')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_sent', to='account.profile', verbose_name='profile_id - Кто поставил лайк/дизлайк')),
            ],
            options={
                'verbose_name': 'Лайк-Дизлайк',
                'verbose_name_plural': 'Лайки-Дизлайки',
            },
        ),
    ]
