# Generated by Django 4.1.7 on 2023-03-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likedislike', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likedislike',
            old_name='who_liked',
            new_name='who_user_liked_id',
        ),
        migrations.RenameField(
            model_name='likedislike',
            old_name='whom_liked',
            new_name='whom_user_liked_id',
        ),
    ]
