# Generated by Django 4.0.1 on 2023-03-31 09:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SP', 'Sport'), ('AT', 'Art'), ('MS', 'Music'), ('SD', 'Self development'), ('CN', 'Creation'), ('AR', 'Another')], default='SP', max_length=2),
            preserve_default=False,
        ),
    ]
