# Generated by Django 4.0.1 on 2023-03-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_interests_remove_profile_interests_profile_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
    ]
