# Generated by Django 4.0.1 on 2023-03-31 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_interests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(choices=[('SP', 'Sport'), ('AT', 'Art'), ('MS', 'Music'), ('SD', 'Self development'), ('CN', 'Creation'), ('AR', 'Another')], default='AR', max_length=2),
            preserve_default=False,
        ),
    ]
